=== jsalmat0910/LMGSI_UD4/LabXML/5.Practicas_CFGS/Practicas_CFGS.dtd
<!ELEMENT practica (alumno+)>
<!ELEMENT alumno (nif, resultado, observaciones, IP)>
    <!ATTLIST alumno codigo CDATA #REQUIRED>
<!ELEMENT nif (#PCDATA)>
<!ELEMENT resultado (#PCDATA)>
<!ELEMENT observaciones (#PCDATA)>
<!ELEMENT IP (#PCDATA)>

=== jsalmat0910/LMGSI_UD4/LabXML/5.Practicas_CFGS/Practicas_CFGS_D.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE practica SYSTEM "Practicas_CFGS.dtd">
<practica>
    <alumno codigo="1">
        <nif>35481065F</nif>
        <resultado>Apto</resultado>
        <observaciones>Campo no obligatorio</observaciones>
        <IP></IP>
    </alumno>
    <alumno codigo="2">
        <nif>45869574X</nif>
        <resultado>Apto</resultado>
        <observaciones>Campo no obligatorio</observaciones>
        <IP></IP>
    </alumno>
    <alumno codigo="3">
        <nif>12657891S</nif>
        <resultado>Apto</resultado>
        <observaciones>Campo no obligatorio</observaciones>
        <IP></IP>
    </alumno>
    <alumno codigo="4">
        <nif>26523145F</nif>
        <resultado>Apto</resultado>
        <observaciones>Campo no obligatorio</observaciones>
        <IP></IP>
    </alumno>
    <alumno codigo="5">
        <nif>32132545X</nif>
        <resultado>No apto</resultado>
        <observaciones>Campo no obligatorio</observaciones>
        <IP></IP>
    </alumno>
</practica>
