=== jsalmat0910/LMGSI_UD4/LabXML/9.Editorial 2/Editorial.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:annotation>
        <xs:documentation xml:lang="ES-es">
        Esquema para el alta de una editorial de libros en sede central
        <fecha> 28/1/2022 </fecha>
        <autor> Juan Ram√≥n Salguero Mateos </autor>
        </xs:documentation>
    </xs:annotation>
    <xs:element name="edicion">
        <xs:complexType>
        <xs:sequence>
            <xs:element name="cabecera">
            <xs:complexType>
                <xs:sequence>
                <xs:element type="xs:string" name="descripcion"/>
                <xs:element type="xs:date" name="fecha"/>
                </xs:sequence>
            </xs:complexType>
            </xs:element>
            <xs:element name="tabla">
            <xs:complexType>
                <xs:sequence>
                <xs:element name="region" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                    <xs:sequence>
                        <xs:element name="trimestre" maxOccurs="unbounded" minOccurs="0">
                        <xs:complexType>
                            <xs:sequence>
                            <xs:element type="xs:string" name="librosVendidos"/>
                            </xs:sequence>
                            <xs:attribute type="xs:byte" name="codigo" use="optional"/>
                        </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                    <xs:attribute type="xs:string" name="codigo" use="optional"/>
                    </xs:complexType>
                </xs:element>
                </xs:sequence>
            </xs:complexType>
            </xs:element>
        </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== jsalmat0910/LMGSI_UD4/LabXML/8.Editorial/Editorial_X.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<edicion xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="Editorial.xsd">
    <informe>
        <descripcion>Informe de ventas para las regiones Norte, Centro, Sur</descripcion>
        <fecha>2009-12-30</fecha>
        <region codigo="norte">
            <trimestre codigo="1">
                <librosVendidos>24000</librosVendidos>
            </trimestre>
            <trimestre codigo="2">
                <librosVendidos>38600</librosVendidos>
            </trimestre>
            <trimestre codigo="3">
                <librosVendidos>NO INFO</librosVendidos>
            </trimestre>
            <trimestre codigo="4">
                <librosVendidos>NO INFO</librosVendidos>
            </trimestre>
        </region>
        <region codigo="centro">
            <trimestre codigo="1">
                <librosVendidos>NO INFO</librosVendidos>
            </trimestre>
            <trimestre codigo="2">
                <librosVendidos>16080</librosVendidos>
            </trimestre>
            <trimestre codigo="3">
                <librosVendidos>25000</librosVendidos>
            </trimestre>
            <trimestre codigo="4">
                <librosVendidos>29000</librosVendidos>
            </trimestre>
        </region>
        <region codigo="sur">
            <trimestre codigo="1">
                <librosVendidos>27000</librosVendidos>
            </trimestre>
            <trimestre codigo="2">
                <librosVendidos>31400</librosVendidos>
            </trimestre>
            <trimestre codigo="3">
                <librosVendidos>40100</librosVendidos>
            </trimestre>
            <trimestre codigo="4">
                <librosVendidos>30000</librosVendidos>
            </trimestre>
        </region>    
    </informe>
</edicion>
