=== jsalmat0910/LMGSI_UD4/LabXML/6.Modulo_CFGS/Modulo_CFGS.dtd
<!ELEMENT modulo (nombre*)>
<!ELEMENT nombre (contenidos*)>
    <!ATTLIST contenidos codigo CDATA #REQUIRED>
<!ELEMENT contenidos (bloque*)>
<!ELEMENT bloque (titulo, descripcion)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>

=== jsalmat0910/LMGSI_UD4/LabXML/6.Modulo_CFGS/Modulo_CFGS_D.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE modulo SYSTEM "Modulo_CFGS.dtd">
<modulo>
    <curso codigo="1">
        <nombre>
            <contenidos>
                <bloque>
                    <titulo>Lenguaje de Marcas</titulo>
                    <descripcion>Se utiliza HTML, XML, C++,...</descricion>
                </bloque>
            </contenidos>
        </nombre>
    </curso>
    <curso codigo="2">
        <nombre>
            <contenidos>
                <bloque>
                    <titulo>Entorno de Desarrollo</titulo>
                    <descripcion>Se aprendera a realizar proyectos de diferentes formas.</descricion>
                </bloque>
            </contenidos>
        </nombre>
    </curso>
    <curso codigo="3">
        <nombre>
            <contenidos>
                <bloque>
                    <titulo>Programación</titulo>
                    <descripcion>Se estudia la programación por java, python, por bloques ,...</descricion>
                </bloque>
            </contenidos>
        </nombre>
    </curso>
</modulo>
